# Generated by Django 5.2.3 on 2025-07-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_role',
            field=models.CharField(blank=True, help_text="Custom description of the client's role (free text)", max_length=100, null=True),
        ),
    ]
