# Generated by Django 5.2.3 on 2025-07-09 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0), help_text='End time of the booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), help_text='Start time of the booking'),
            preserve_default=False,
        ),
    ]
